# Generated by Django 5.2.8 on 2025-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_seller_delete_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='نسبة الخصم، مثال: 10 = خصم 10%', max_digits=5),
        ),
    ]
