# Generated by Django 5.2.8 on 2026-07-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='client_scret',
            new_name='client_secret',
        ),
    ]
