# Generated by Django 5.2.8 on 2025-11-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='code',
            name='is_verified',
        ),
    ]
