"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%40mwv3so-73_m3421y1d7znm_3oysx+fjn=oo=pw@f93c0_lo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'auth_system',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'address',
    'product',
    'cart',
    'order',
    'payment',
    'django_celery_beat',
    'django_celery_results',
    
]
AUTH_USER_MODEL = 'auth_system.CustomUser'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True #بدونه الكوكي مش هتتبعت.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.dev']

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "auth_system.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter"
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10  
}


SIMPLE_JWT = {
    "BLACKLIST_AFTER_ROTATION": True,
}
from decouple import config

# Email Config
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# Cookies Settings
ACCESS_COOKIE_NAME = "access_token"
REFRESH_COOKIE_NAME = "refresh_token"
ACCESS_COOKIE_MAX_AGE = 60 * 5  # 5 دقايق
REFRESH_COOKIE_MAX_AGE = 7 * 24 * 3600  # أسبوع
COOKIE_HTTPONLY = True
COOKIE_SAMESITE = "Lax"
COOKIE_SECURE = False  # خليها True لو شغال HTTPS
COOKIE_PATH = "/"

# Google OAuth2
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = config("GOOGLE_REDIRECT_URI")


import os

# مسار حفظ ملفات الوسائط (الصور / الفيديو / الملفات)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AVAILABLE_PAYMENT_METHODS = [
    ("COD", "Cash on Delivery"),
    ("EPAY", "E-payment"),
]



CELERY_BROKER_URL = "redis://localhost:6379/0" # ﻣﺜﺎل ﻟﻮ ﺗﺴﺘﺨﺪم Redis
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"


PAYMOB_PAYMENT_METHODS = [
    "mobile wallet",
    "paypal",
    "online card"
] # طرق الدفع المدعومة في Paymob

COOLING_PERIOD_AFTER_EXPIRY = 10 # 10 دقيقة
MAX_UNPAID_ORDERS_PER_USER = 3 # أقصى عدد أوردرات غير مدفوعة لكل مستخدم
MAX_QTY_PER_ITEM = 15 # أقصى كمية لكل منتج في أي order
PAYMENT_LINK_LIFETIME_SECONDS = 600  # 10 دقيقة
SYSTEM_PAYMENT_EXPIRE_MINUTES = 15  # 15 دقيقة
ORDER_EXPIRE_MINUTES = 15  # 15 دقيقة
COOLING_PERIOD_AFTER_EXPIRY = 10 # 10 دقيقة
COD_ORDER_EXPIRE_DAYS = 3  # 3 أيام

PAYMOB_INTEGRATION_ID = 5492078
PAYMOB_SECRET_KEY = config("PAYMOB_SECRET_KEY")
PAYMOB_PUBLIC_KEY = config("PAYMOB_PUBLIC_KEY")
PAYMOB_REDIRECTION_URL = config("PAYMOB_REDIRECTION_URL")
PAYMOB_PAYMENT_METHODS = [
    "mobile wallet",
    "paypal",
    "online card"
] # طرق الدفع المدعومة في Paymob
PAYMOB_HMAC_TOKEN = config("PAYMOB_HMAC_TOKEN")
